name: windnav-release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: [opensuse-basic]
    container:
      image: opensuse/tumbleweed:basic
      volumes:
        - /run/docker.sock:/var/run/docker.sock

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          set -e
          zypper --non-interactive refresh
          zypper --non-interactive install -y docker

      - name: Set up QEMU
        uses: actions/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Set up Docker metadata
        id: meta
        uses: actions/metadata-action@v5
        with:
          images: |
            ${{ vars.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Log in to registry
        uses: actions/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: actions/build-push-action@v6
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
